In [1]:
import pandas as pd
import pickle
from pickle_loader import pickle_loader
import numpy as np

In [2]:
final_fundamental_dict = pickle_loader('final_fundamental_dict.pickle')
modeling_attributes = pickle_loader("fundamental_modeling_attributes.pickle")

In [3]:
modeling_attributes

{'Accounts Receivable',
 'Basic Average Shares',
 'Basic EPS',
 'Beginning Cash Position',
 'Capital Expenditure',
 'Capital Stock',
 'Cash And Cash Equivalents',
 'Cash Cash Equivalents And Short Term Investments',
 'Cash Flow From Continuing Financing Activities',
 'Cash Flow From Continuing Investing Activities',
 'Cash Flow From Continuing Operating Activities',
 'Change In Working Capital',
 'Changes In Cash',
 'Common Stock',
 'Common Stock Equity',
 'Current Assets',
 'Current Liabilities',
 'Diluted Average Shares',
 'Diluted EPS',
 'Diluted NI Availto Com Stockholders',
 'EBIT',
 'End Cash Position',
 'Financing Cash Flow',
 'Free Cash Flow',
 'Gains Losses Not Affecting Retained Earnings',
 'Invested Capital',
 'Investing Cash Flow',
 'Long Term Debt',
 'Long Term Debt And Capital Lease Obligation',
 'Net Income',
 'Net Income Common Stockholders',
 'Net Income Continuous Operations',
 'Net Income From Continuing And Discontinued Operation',
 'Net Income From Continuing Opera

In [4]:
def percentage_diff(arr):
    x1 = arr[1:]
    x0 = arr[:-1]
    
    np.seterr(divide='ignore', invalid='ignore')
    diff = ((x1 - x0) / x0) * 100 
    return diff

In [10]:
def get_non_impute_data(final_fundamental_dict, modeling_attributes):
    
    tickers = list(final_fundamental_dict.keys())
    final_dataset = {}
    
    for ticker in tickers:
        data = final_fundamental_dict[ticker]
        ticker_attr = set(data.index)
        final_ticker_dataset = np.zeros((len(modeling_attributes), 3))
        
        for i, attr in enumerate(modeling_attributes):
            if attr in ticker_attr:
                attr_array = np.array(list(data.loc[attr]))
                
                if ticker == 'AOS':
                    print(ticker, attr, attr_array)
                if len(attr_array) > 4:
                    attr_array = attr_array[:-1]
                
                
                attr_array = percentage_diff(attr_array)
                if ticker == 'AOS':
                    print(attr_array)
                final_ticker_dataset[i, :] = attr_array
            else:
                attr_array = np.full(3, np.nan)
                final_ticker_dataset[i, :] = attr_array
            
        final_ticker_df = pd.DataFrame(final_ticker_dataset, columns = ['Q1', 'Q2', 'Q3'], index = list(modeling_attributes))
        final_dataset[ticker] = final_ticker_df
    
    return final_dataset

In [11]:
final_dataset_non_impute = get_non_impute_data(final_fundamental_dict, modeling_attributes)

AOS Cash Cash Equivalents And Short Term Investments [4.097e+08 4.960e+08 4.818e+08 4.171e+08]
[ 21.06419331  -2.86290323 -13.42880863]
AOS Accounts Receivable [5.889e+08 5.868e+08 5.812e+08 5.642e+08]
[-0.35659705 -0.95432856 -2.92498279]
AOS Payables And Accrued Expenses [7.890e+08 8.239e+08 8.606e+08 8.304e+08]
[ 4.42332066  4.45442408 -3.50917964]
AOS Operating Revenue [9.608e+08 9.664e+08 9.361e+08 8.742e+08]
[ 0.58284763 -3.13534768 -6.6125414 ]
AOS Long Term Debt And Capital Lease Obligation [2.220e+08 3.559e+08 3.569e+08 3.045e+08]
[ 60.31531532   0.2809778  -14.68198375]
AOS Net Income Continuous Operations [ 1.570e+08  1.269e+08 -1.201e+08  1.098e+08]
[ -19.17197452 -194.64144996 -191.42381349]
AOS Capital Stock [2.949e+08 2.949e+08 2.949e+08 2.950e+08]
[0.        0.        0.0339098]
AOS Financing Cash Flow [-1.937e+08 -9.750e+07 -1.107e+08 -1.409e+08]
[-49.66442953  13.53846154  27.28093948]
AOS Tangible Book Value [9.235e+08 8.255e+08 7.801e+08 7.787e+08]
[-10.61180292  -5

In [7]:
final_dataset_non_impute['AOS'].head()


Q1        Q2  \
Cash Cash Equivalents And Short Term Investments  21.064193 -2.862903   
Accounts Receivable                               -0.356597 -0.954329   
Payables And Accrued Expenses                      4.423321  4.454424   
Operating Revenue                                  0.582848 -3.135348   
Long Term Debt And Capital Lease Obligation       60.315315  0.280978   

                                                         Q3  
Cash Cash Equivalents And Short Term Investments -13.428809  
Accounts Receivable                               -2.924983  
Payables And Accrued Expenses                     -3.509180  
Operating Revenue                                 -6.612541  
Long Term Debt And Capital Lease Obligation      -14.681984

In [16]:
final_dataset_non_impute['ACN'].index

Index(['Basic Average Shares', 'EBIT', 'Invested Capital',
       'Diluted Average Shares', 'Diluted NI Availto Com Stockholders',
       'Cash Cash Equivalents And Short Term Investments',
       'Cash And Cash Equivalents', 'Financing Cash Flow', 'Capital Stock',
       'Net Interest Income', 'Stockholders Equity', 'Free Cash Flow',
       'Normalized Income', 'Cash Flow From Continuing Financing Activities',
       'Net Income', 'Ordinary Shares Number', 'Operating Cash Flow',
       'Cash Flow From Continuing Operating Activities', 'Common Stock',
       'Net Income Continuous Operations', 'Net Tangible Assets',
       'Total Non Current Assets', 'Capital Expenditure',
       'Total Liabilities Net Minority Interest', 'Long Term Debt',
       'Tangible Book Value', 'Share Issued', 'Investing Cash Flow',
       'Change In Working Capital', 'Total Debt', 'Basic EPS', 'Tax Provision',
       'End Cash Position', 'Tax Effect Of Unusual Items',
       'Gains Losses Not Affecting Retaine

In [12]:
with open("/Users/marcs/OneDrive/Documents/stock_analysis2/final_dataset_non_impute.pickle", 'wb') as f:
        pickle.dump(final_dataset_non_impute, f)

In [12]:
x0 = 43600000
x1 = -9800000

(x1 -x0) /x0

-1.224770642201835